### ISSUE TITLE
Error when opening mail with schedule request

### ISSUE THREAD

**Issue by DoktorAerzt** [texxasrulez/caldav_calendar#1]
I installed caldav_calendar in my roundcubemail instance. 
The calendar sync with nextcloud is working. 
When im open a mail with an schedule request, then i get an internal server error. 

Roundcubemail version: 1.4.2
Caldav_Calendar version: 0.6.4

```
[03-Feb-2020 11:24:55 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function get_event() on null in /var/www/html/roundcubemail/plugins/calendar/calendar.php:2880
Stack trace:
#0 /var/www/html/roundcubemail/plugins/calendar/calendar.php(2899): calendar->find_event(Array, 9)
#1 /var/www/html/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(494): calendar->event_itip_status()
#2 /var/www/html/roundcubemail/index.php(294): rcube_plugin_api->exec_action('calendar.itip-s...')
#3 {main}
  thrown in /var/www/html/roundcubemail/plugins/calendar/calendar.php on line 2880
```

Do you need more information ?

**Comment by texxasrulez** [comment]
I have discovered a few of these issues with the itip features recently. I am the only developer on this project and didn't test those features as good as I should have. I did upload a new commit last night for the itip issues I discovered. If you haven't downloaded any commit within the last 12 hours, would you please download and install the latest commit, not release but commit, it should resolve your issue. If not, just let me know you tried the latest commit and still get this error, I will investigate and provide a fix.

I will inform you I will be out of town for the rest of the week to visit a friend who is not doing too well right now and will not be able to check into until then. 

As always, thanks for your input and I hope the latest commit will fix your issue so you will not have to wait a week for a solution.

**Comment by DoktorAerzt** [comment]
Now it´s works. Thank you
