### ISSUE TITLE
Please provide initial MySQL commands

### ISSUE THREAD

**Issue by Miyamoto72** [texxasrulez/caldav_calendar#11]
Well - the topic is pretty straightforward ;-)
I'd like to use your plugin, but my host runs MySQL, not Postgres. Upon trying to import the postgres.initial.sql file I get several errors complaining about syntax errors:

> ERROR 1071 (42000) at line 1 in file: 'postgres.initial.sql': Specified key was too long; max key length is 3072 bytes
> ERROR 1071 (42000) at line 11 in file: 'postgres.initial.sql': Specified key was too long; max key length is 3072 bytes
> ERROR 1071 (42000) at line 23 in file: 'postgres.initial.sql': Specified key was too long; max key length is 3072 bytes
> ERROR 1064 (42000) at line 33 in file: 'postgres.initial.sql': You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"system" (name, value) VALUES ('calendar-version', '2016011300')' at line 1
> 

Well, the last line was pretty easy to solve, but I can't get my head to understand the other lines. so far.
The last line needs to be like this for MySQL:
`INSERT INTO system(name,value) VALUES ('calendar-version', '2016011300');`

AFAICT MySQL doesn't know what to do about the CONSTRAINT directive - nor do I ;-)

Maybe you do?

**Comment by texxasrulez** [comment]
The postgres schema was added by another user. I have no way to test as I only have mysql. I will leave  this issue open so others may can help you out on this. I am sorry, but I am limited on what I can test with ...

**Comment by texxasrulez** [comment]
I misunderstood what you wrote. I am running sql and the schema is located in /calendar/drivers/caldav/sql/
