### ISSUE TITLE
Existing Calendar content doesn't show up

### ISSUE THREAD

**Issue by douwezijlstra-frl** [texxasrulez/caldav_calendar#12]
Hi!

I have some issues with the calendaring plugin; it doens't show existing events. It does list all the calendars I have (3), and new events created in Roundcube are added and synced.

console.log says:
[11-Mar-2020 14:22:31 +0000]: <2494a8b1> caldav_driver: Sync period active: Assuming calendar "4102" to be in sync.

Seems like existing events aren't added to the 'Events' table

The CalDAV server is a Horde Groupware server based on Kronolith.

**Comment by texxasrulez** [comment]
I do not support Horde Groupware and there is already an open issue pertaining to Horde Groupware, so I am closing this issue.
