### ISSUE TITLE
Is it still mandatory to have Nextcloud username/password to be the same as RoundCube ones ?

### ISSUE THREAD

**Issue by ericxuo** [texxasrulez/caldav_calendar#13]
Hi,

I'd like to integrate my NextCloud Calendar into RoundCubeMail.
But you wrote in the Wiki page :

> VERY IMPORTANT
> Your username and password must be the same for Nextcloud and Roundcube to work properly. There are no plans at this time to implement. My advice is just create your users in Nextcloud using the exact username required to login to your email server. You should have no issues.

Is it still the case ? Because I've seen in the file : 
plugins/caldav_calendar/calendar/config.inc.php
lines such : 

> // Pre-installed calendars, added at first access to calendar section
> // Caldav driver is supported only
>  $config['calendar_preinstalled_calendars'] = array(
>     'Nextcloud' => array(
> 			'driver'       => 'caldav',
> 			'name'         => 'NextCloud_calendar',
> 			'caldav_user'  => 'nextCloudUser',
> 			'caldav_pass'  => 'nextCloudPasswordFor_nextCloudUser',
> 			'caldav_url'   => 'https://nextcloud.domain.fr/remote.php/dav/calendars/nextCloudUser/default/',
> 			'color' 	   =>  '',
> 			'showAlarms'   => 1));
> 

Is it still mandatory to have roundCubeMail username and nextCloud username (and password) to be the same ? From the lines above, it seems possible to have a dedicated nextCloud username because it would not be necessary to have to define the "caldav_user" and "caldav_pass" fields.

Regards.

Xuo.

**Comment by texxasrulez** [comment]
For ease and convenience, yes, same username and password is required. I have no plans on implementing anything else in the future, sorry, but just do not have that kind of time to devote to what would be a major code base overhaul. Thank you for your interest..

**Comment by ericxuo** [comment]
Hi,

Thank you for the answer (even though it is not the one I was expecting :))

Regards.

Xuo.
