### ISSUE TITLE
Help with Readme

### ISSUE THREAD

**Issue by meaz** [texxasrulez/caldav_calendar#14]
Hi,

In [https://github.com/kolab-roundcube-plugins-mirror/calendar](https://github.com/kolab-roundcube-plugins-mirror/calendar) it is said to:
- Initialize the calendar database with `bin/initdb.sh --dir=plugins/calendar/drivers/database/SQL
`
- Build css styles for the Elastic skin

Does that need to be done when using [https://github.com/texxasrulez/caldav_calendar](https://github.com/texxasrulez/caldav_calendar) ?

Also, it is said on [https://github.com/texxasrulez/caldav_calendar](https://github.com/texxasrulez/caldav_calendar) to `Import the corresponding (MySQL, Postgres) initial SQL schema located in calendar/drivers/*/SQL/ folder to your Roundcube database.` How do you do that?

**Comment by ericxuo** [comment]
Hi,

For your 2 first questions, I don't know. As far as I remember, I didin't do it.
To import sql databases (mysql in this case) :
/usr/bin/mysql --user=root --password=Root_Database_Password roundcubemail < drivers/database/SQL/mysql.initial.sql
And do the same for all directories under the caldav_calendar/drivers directory.

Regards.

Xuo.

**Comment by meaz** [comment]
thanks!
