### ISSUE TITLE
Refresh data

### ISSUE THREAD

**Issue by marcoprotasi** [texxasrulez/caldav_calendar#15]
hi how is it possible to add a refresh action to update the calendar when more users work on it?
Sometimes users edit events from the mail client and changes to the webmail are not visible until a user makes a change from the webmail, as if resyncing the data to the server did not take place.
Thank you

**Comment by marcoprotasi** [comment]
I answer myself, settings -> Calendar Sync Interval

;)

**Comment by texxasrulez** [comment]
I would have gave you the same answer. Good job
