### ISSUE TITLE
Internal Server Error 500 in first sync

### ISSUE THREAD

**Issue by Offerel** [texxasrulez/Caldav_Calendar#16]
I have installed your AddOn to Roundcube 1.3.3 (and also RCMCARDDAV). The server is on nginx 1.10.x and php 7.0.x on a small raspberry pi. CalDAV is sabreDAV 3.20 on the same server, i accessing it without external access on localhost:81 via basic auth. since its only a internal server this is no security problem for me.

The calendars are correctly added during the initial sync and added to the database. Also a small set of first events are imported. But the process does not come to an end. Im getting entrys in nginx log like the following after some time:
```
"GET /mail/?_task=calendar&source=1&driver=caldav_driver&_action=load_events&start=1510527600&end=1511132400&_=15109152
45368 HTTP/2.0" 500 244 "https://sub.mydomain.com/mail/?_task=calendar" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"
```
Im accessing roundcube via a external URL which is secured with https. Internal access works via http only.

Is there anything i can do to find out, why i get the internal server error?

**Comment by Offerel** [comment]
If i turn on debugging in config.inc.php i get the following error:

`PHP Fatal error:  Maximum execution time of 120 seconds exceeded in /var/www/roundcubemail-1.3.3/plugins/calendar/drivers/caldav/caldav_driver.php on`

I can't fully understand this, because max_execution_time in the correct php.ini is at 300. I don't know why it here stops after 120 seconds. I have tried to extend the running time to 300 with ini_set(max_execution_time, 300) at the beginning of caldav_driver.php. This works, but with this, i get the same error, except this time it stops after 300 secs. I don't know why it takes this long time.

**Comment by texxasrulez** [comment]
I cannot reproduce your error. How big is your calendar?

**Comment by incastrix** [comment]
maybe here is the problem: https://github.com/texxasrulez/Caldav_Calendar/blob/e4184a68f60384b0bf85037d5c3e27348dbc11fc/calendar/drivers/caldav/caldav_driver.php#L671

**Comment by Offerel** [comment]
I have seen that line also. But I didn't know if I can anything do. Since there are not all events affected, I assume that this lines of code are not involved by every event. Maybe it is ok if I comment this lines, so that this part is not executed, but I don't know if this could make problems, since I don't know what this does with the event.

**Comment by incastrix** [comment]
In my case, the problem was with recurrence events and really don't understand what that pice of code should do.

**Comment by Offerel** [comment]
could you fix it for you or find a workaround, so that it works afterwards for you?

**Comment by incastrix** [comment]
I just comment that part of code.

**Comment by Offerel** [comment]
and your recurrences? any visible effect?

**Comment by Offerel** [comment]
I got it to work, but unfortunately, i get the same result as with all other CalDAV plugins for Roundcube. If i update a calendar, i get most of the events duplicated. I have no explanation.

So i have written a RC Plugin to integrate CalDAVZap directly in to RC. I know, its only a dirty workaround, but it works at least for me.
