### ISSUE TITLE
"Save to calendar" action on an attached ics results in: "Application Error (500): No driver name found in GPC."

### ISSUE THREAD

**Issue by apircalabu** [texxasrulez/caldav_calendar#16]
CentOS 7.7, PHP 7.4.5 run as php-fpm with Roundcube Webmail 1.4.3
calendar is connecting to a Nextcloud 16.0.9 instance and the logged in user has access to 5 calendars.
Roundcube plugins:
archive	3.4	GPLv3+	
attachment_reminder	1.1	GPLv3+	
automatic_addressbook_ng		GPL-3.0+	Download
caldav_calendar	0.6.0.2	GPL-3.0-only	Download
carddav	3.0.3	GPL-2.0	Download
contextmenu	3.1	GPL-3.0	Download
database_attachments	1.2	GPLv2	
emoticons	2.0	GPLv3+	
hide_blockquote	1.0	GPLv3+	
ident_switch		GPL-3.0+	Download
jqueryui	1.12.0	GPLv3+	
libcalendaring	0.7.0.0	GPL-3.0-only	Download
libkolab	--		
managesieve	9.3	GPLv3+	
markasjunk	2.0	GPLv3+	
newmail_notifier	0.8	GPLv3+	
new_user_dialog	2.4	GPLv3+	
rcguard	1.2.2	GPLv3+	Download
swipe	0.2	GPL-3.0	Download
twofactor_gauthenticator	2.0.0	MIT	Download
vcard_attachments	4.1	GPLv3+	
zipdownload	3.4	GPLv3+

How to reproduce:
1. In the Calendar page click on the next event (could be any?) and from Options select Download. Save it as ics.
2. Compose an email to yourself and attach the resulted ics.
3. Open the email, click on the down arrow and select "Save to calendar", which will result in "Application Error (500): No driver name found in GPC." error in Roundcube.

Roundcube logs in /var/log/messages this corresponding entry:
Apr 16 22:04:15 mail roundcube-mail: <q6q4suoh> PHP Error: No driver name found in GPC. (POST /?_task=calendar&_framed=1&_action=mailimportattach)

**Comment by texxasrulez** [comment]
This is a confirmed and already submitted error. I do appreciate you interest. I am still working on this particular error
