### ISSUE TITLE
compatibility with php 7.2

### ISSUE THREAD

**Issue by MAT-WEISS-2017** [texxasrulez/Caldav_Calendar#17]
I had to update my ArchLinux to php 7.2. Now the caldav calendars will not work anymore. This is probably due to the lack of support for "mcrypt" in the new php version.

When should "mcrypt" be replaced with "openssl"? It's already on the ToDo list. Is there a plan?

Maybe it's also an option to replace "mcrypt" with "libsodium"?

Currently I had to deactivate your plugin. This is sad because everything worked well up to the previous php version.

Here are my roundcube error messages:

```
PHP Warning:  Use of undefined constant MCRYPT_BlOWFISH - assumed 'MCRYPT_BlOWFISH' (this will throw an Error in a future version of PHP) in /usr/share/webapps/roundcubemail/plugins/calendar/drivers/caldav/caldav_driver.php on line 1922

[04-Dec-2017 14:08:05 Europe/Berlin] PHP Warning:  Use of undefined constant MCRYPT_MODE_CBC - assumed 'MCRYPT_MODE_CBC' (this will throw an Error in a future version of PHP) in /usr/share/webapps/roundcubemail/plugins/calendar/drivers/caldav/caldav_driver.php on line 1922

[04-Dec-2017 14:08:05 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function mcrypt_get_iv_size() in /usr/share/webapps/roundcubemail/plugins/calendar/lib/encryption.php:106
```

**Comment by texxasrulez** [comment]
Yeah, unfortunately I do not have time right now to update. I moved half way across the US and started a new job, so that consumes a lot of my free time. I would love some help in getting rid of mycrypt. As you pointed out it is on my To Do list ... Maybe one day I will get a wild hair and do it, but I don't see having that much time for at least 6 months. Thank you for your interest in this project and hopefully this will get done.

**Comment by MAT-WEISS-2017** [comment]
Here's my little quick dirty fix for switching to openssl:

I changed the file "plugins/calendar/drivers/caldav/caldav_driver.php" at the end ...

```
    private function mw_encrypt($data,  $key, $method) {
        $ivSize = openssl_cipher_iv_length($method);
        $iv = openssl_random_pseudo_bytes($ivSize);
        $encrypted = openssl_encrypt($data, $method, $key, OPENSSL_RAW_DATA, $iv);
        $encrypted = base64_encode($iv . $encrypted);
        return $encrypted;
    }
    private function mw_decrypt($data, $key, $method) {
        $data = base64_decode($data);
        $ivSize = openssl_cipher_iv_length($method);
        $iv = substr($data, 0, $ivSize);
        $data = openssl_decrypt(substr($data, $ivSize), $method, $key, OPENSSL_RAW_DATA, $iv);
        return $data;
    }
    private function _decrypt_pass($pass) {
        $method = 'AES-256-CBC';
        $password = 'FvK2znEU73x5yAeC6iRbp9r-8sPQgDMZ';
        $key = hash('sha256', $password);
        return $this->mw_decrypt($pass, $key, $method);
    }
    private function _encrypt_pass($pass) {
        $method = 'AES-256-CBC';
        $password = 'FvK2znEU73x5yAeC6iRbp9r-8sPQgDMZ';
        $key = hash('sha256', $password);
        return $this->mw_encrypt($pass, $key, $method);
    }
```

Since this adaptation I can use the plugin again.

**Comment by mkerstner** [comment]
Cheers! Works perfectly on reference PHP 7.2.5 system

**Comment by gloony** [comment]
I make a change.

Add this on calendar/config.inc.php
`$config['calendar_crypt_key'] = "32randomchararchter";
$config['calendar_iv_key'] = "16randomcharcharacter";`

And on calendar/drivers/caldav/caldav_driver.php remove line 1920 to 1929, and repace fonction with
`    private function _decrypt_pass($pass) {
        $p = base64_decode($pass);
        $e = new Encryption($this->crypt_key, $this->iv_key);
        return $e->decrypt($p);
    }
    private function _encrypt_pass($pass) {
        $e = new Encryption($this->crypt_key, $this->iv_key);
        $p = $e->encrypt($pass);
        return base64_encode($p);
    }`

And finally the calendar/lib/encryption.php change completly by 
`<?php
/**
 * A class to handle secure encryption and decryption of arbitrary data
 * Copyright http://stackoverflow.com/users/338665/ircmaxell
 * http://stackoverflow.com/questions/5089841/php-2-way-encryption-i-need-to-store-passwords-that-can-be-retrieved
 * 
 *
 * Note that this is not just straight encryption.  It also has a few other
 *  features in it to make the encrypted data far more secure.  Note that any
 *  other implementations used to decrypt data will have to do the same exact
 *  operations.
 *
 * Security Benefits:
 *
 * - Uses Key stretching
 * - Hides the Initialization Vector
 * - Does HMAC verification of source data
 *
 */
class Encryption {

    /**
     * @var string $PassPhrase The mcrypt cipher to use for this instance
     */
    private static $PassPhrase = null;

    /**
     * @var string $PassIV The mcrypt cipher to use for this instance
     */
    private static $PassIV = null;

    /**
     * Encrypt the supplied data using the supplied key
     *
     * @param string $PassPhrase The data to encrypt
     * @param string $PassIV  The key to encrypt with
     *
     * @returns string The encrypted data
     */
    public function __construct($PassPhrase, $PassIV){
        $this->PassPhrase = $PassPhrase;
        $this->PassIV = $PassIV;
    }

    /**
     * Encrypt the supplied data using the supplied key
     *
     * @param string $data The data to encrypt
     *
     * @returns string The encrypted data
     */
    public static function encrypt($String){
        $Method = 'AES-256-CBC';
        $Key = hash('sha256', static::$PassPhrase);
        $IV = substr(hash('sha256', static::$PassIV), 0, 16);
        return openssl_encrypt($String, $Method, $Key, 0, $IV);
    }

    /**
     * Decrypt the data with the provided key
     *
     * @param string $data The encrypted datat to decrypt
     *
     * @returns string|false The returned string if decryption is successful
     *                           false if it is not
     */
    public static function decrypt($String){
        $Method = 'AES-256-CBC';
        $Key = hash('sha256', static::$PassPhrase);
        $IV = substr(hash('sha256', static::$PassIV), 0, 16);
        return openssl_decrypt($String, $Method, $Key, 0, $IV);
        // return '2DmfW-ikG6C-XRTGW-fsBpp-sTBHz';
    }
}`

This work well for me, I don't know if I forget something in his code, but it is a more cleaner start I guess.

**Comment by texxasrulez** [comment]
Thank you MAT-WEISS-2017, I have merged your fix into my branch. I have it running on PHP 7.2.11 and is working just fine. Thanks for your help

**Comment by MAT-WEISS-2017** [comment]
Hi texxasrulez,
please add some changes so that the error messages disappear.

**1.**
```
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/share/webapps/roundcubemail/plugins/libcalendaring/libvcalendar.php on line 720
```

```
line 720
718-                // skip dupes
719-                if ($seen[$prop->value.':'.$fbtype]++)
720:                    continue 2;
721-
```

**2.**
```
PHP Warning:  Use of undefined constant RCMAIL_CHARSET - assumed 'RCMAIL_CHARSET' (this will throw an Error in a future version of PHP) in /usr/share/webapps/roundcubemail/plugins/calendar/lib/calendar_ui.php on line 301
```

```
line 299 and 301
299:    if (defined('RCUBE_CHARSET')) {
300:        $charset = RCUBE_CHARSET;
301-    } elseif (defined('RCMAIL_CHARSET')) {
302-        $charset = RCMAIL_CHARSET;
303-    } else {
304-        $charset = $this->rc->config->get('default_charset');
305-    }
```

**3.**
```
PHP Warning:  Use of undefined constant JS_OBJECT_NAME - assumed 'JS_OBJECT_NAME' (this will throw an Error in a future version of PHP) in /usr/share/webapps/roundcubemail/plugins/calendar/lib/calendar_ui.php on line 646
```

```
line 646
646:        'onclick' => 'JS_OBJECT_NAME' . ".upload_file(this.form)"))) .
647-      html::div('hint', $this->rc->gettext(array('name' => 'maxuploadsize', 'vars' => array('size' => $max_filesize))))
648-    );
649-  }
```

**4.**
```
DAV Error: HTTP error: 401 in /usr/share/webapps/roundcubemail/plugins/calendar/lib/vendor/sabre/dav/lib/DAV/Client.php on line 231 (POST /?_task=calendar&_action=refresh)
```
```
I do not have a solution for this error yet.
```
