### ISSUE TITLE
Every page update add one or more calendar in calendar view with the same name

### ISSUE THREAD

**Issue by Hitman86R** [texxasrulez/caldav_calendar#19]
Hello,
I installed the plugin on roundcube 1.4.4, I state that I use a perfectly working caldav server, after having correctly configured and started the plugin it works but, every access that is made to roundcube the plugin arbitrarily adds a number of calendars equal to you precede it, that is, if I have only one calendar, at the second access they become two with the same name, at the third access they become 4 at the 4 access they become 8 etc.
Can you give me a solution?

if you need more details ask well, but as far as I understand every time you log in to the caldav server to retrieve users' calendars, assign an id that subsequently cannot find and then generate an identical one with a different id . on the caldav server everything remains unchanged but on the roundcube database where the tables for managing calendars have been added calendars increase exponentially with each access

**Comment by texxasrulez** [comment]
I do need details. Logs everything you got. Screenshots would be nice too. Thanks

**Comment by Hitman86R** [comment]
good morning,
as required I'm attaching a series of images, including the log files of the whole plugin, which will surely make you understand the situation. I tend to clarify that the tests I have done at the moment are with the simple refresh of the roundcube page, so I add that not only does this problem arise at every login, but also just the simple update of the page.
Empty database.
![db1 bmp](https://user-images.githubusercontent.com/5153596/80798248-419e1d00-8ba4-11ea-9146-09f328ccdd57.png)
First login.
![round1](https://user-images.githubusercontent.com/5153596/80798262-4c58b200-8ba4-11ea-8b62-dbd7cb181593.png)
![db2](https://user-images.githubusercontent.com/5153596/80798274-524e9300-8ba4-11ea-9c9b-cbc9cb7c580a.png)
Second login.
![round2](https://user-images.githubusercontent.com/5153596/80798306-66929000-8ba4-11ea-8194-d9bb485bf92d.png)
![db3](https://user-images.githubusercontent.com/5153596/80798313-6b574400-8ba4-11ea-8f99-3b6269396496.png)
Third login.
![round3](https://user-images.githubusercontent.com/5153596/80798342-7b6f2380-8ba4-11ea-90e4-bb8c4da2cf11.png)
![db4](https://user-images.githubusercontent.com/5153596/80798352-7f02aa80-8ba4-11ea-9103-619b602b9856.png)
End next the log files.
Error log.
![log error ](https://user-images.githubusercontent.com/5153596/80798406-9b9ee280-8ba4-11ea-8edd-ea45ec75e89b.png)
Console log.
![console log](https://user-images.githubusercontent.com/5153596/80798442-aa859500-8ba4-11ea-8904-dc5bc7b909f5.png)

let me know if anything else is needed

**Comment by texxasrulez** [comment]
Thank you for the prompt screenshots. 
I can not duplicate this issue. 
What database server are you using? 
Can you post any entries from your OS system logs if applicable?
Can you post your config.inc.php too as well?
Let just see if we can figure this out.
I do thank you.

**Comment by Hitman86R** [comment]
As a database I use mysql.

this part is the only one that I have modified of the plugin's config.inc.php file the rest I have not modified:

`// Pre-installed calendars, added at first access to calendar section`
`// Caldav driver is supported only`
` $config['calendar_preinstalled_calendars'] = array(`
`    'Sabredav' => array(`
                     `'driver'       => 'caldav',`
                     `'name'         => '',`
                     `'caldav_user'  => '%u',`
                     `'caldav_pass'  => '%p',`
                     `'caldav_url'   => 'https://sabredav.clan99.tk/calendars/%u/',`
                     `'color'        =>  '',`
                     `'showAlarms'   => 1));`


there is no relevant entry in the registry.

As regards the sabredav server, authenticated using the imap protocol. when creating a new mailbox, through mysql triggers I made sure that a basic calendar and a basic contact list are also created.

The version of sabredav that I use is 3.2.0 downloaded through composer, with the addition of the authentication system via imap available in the master, however compatible with previous versions. The server confirms that it works very well with iOS, eMClient, Android, etc.

If it can be useful, my server uses vobjects 4.2.2

**Comment by texxasrulez** [comment]
OK, so I see that you are using sabredav and not Nextcloud. Unfortunately I do not have that installed to test with. I can only support Nextcloud's caldav since that is what I use and the only reason I forked this project to begin with. I specifically specify that Nextcloud is all I am going to support.
I wished I could help you but I do not have the time or the resources to make this work for every incantation of sabredav. I hope you understand, but hey, that is the beauty of OSS, you are free to fork it and make it your own and make it work for your specific requirements. When I started this, it did not work with Nextcloud, but with hard work and LOTS of time, I now I have a calendar that works flawlessly for me and my needs.
I do appreciate the interest and wish you the best of luck.

**Comment by Hitman86R** [comment]
ok thanks anyway, I was hoping you could at least understand what the problem might be. I will try to find a solution, if I succeed I would be happy to share it with you so that I can make your plugin more flexible and compatible.

**Comment by texxasrulez** [comment]
That would be awesome. I have another repo just for that. to expand and make work with other types of dav servers and plus try to get it feature rich and make it the best dang caldav calendar out there. [Caldav Calendar Texas Edition](https://github.com/texxasrulez/caldav_calendar_te) . I just need help doing so. Thank you and have a great day
