### ISSUE TITLE
Usage with sabreDAV

### ISSUE THREAD

**Issue by Offerel** [texxasrulez/caldav_calendar#2]
Hi there. Since Nextcloud is based heavily on SabreDAV and i can rewrite URL's for Nextcloud also, i wonder if there is way to use different URL schemas as in Nextcloud standard. Could you please make this happen?

Or if you didn't have the time this, do you accept pull requests for this? I'm not sure if i found the time, but it would be a great feature.

**Comment by Offerel** [comment]
OK found it... sorry for the missleading issue

**Comment by texxasrulez** [comment]
It is all good Offerel. I do want to make a caldav calendar that will work for all. If you haven't noticed, I did a lot of restructuring and whatnot to gear up for a second version that I am working on just for this. I am calling it the "Texas Edition". It will take me a month of Sundays (southerner speak for forever) to make it happen. I am trying to find some extra funds so I can be able to have my own server again that I can install whatever I want on to be able to test and pull off. 

In the meantime, I do thank you and hope you have a great week. Peace ... B-)
