### ISSUE TITLE
Recurring EVENT until a date freezes plugin

### ISSUE THREAD

**Issue by archont00** [texxasrulez/Caldav_Calendar#20]
Caldav_Calendar plugin freezes when it tries to sync a calendar event with repeat rule from a date to a date like `RRULE:FREQ=WEEKLY;UNTIL=20180429T050000Z;BYDAY=SU^M` and eventually the connection times out without any event being created. The calendar view does not display any events and keeps trying to "refresh" the events every few minutes.

Creating such an event is not yet supported in Nexctloud / Calendar webapp yet. However, DavDroid (Android sync client) can do that, it syncs with Nexctloud CalDav server and Nextcloud / Calendar app displays the event (although it suggests not to edit the "repeat" rule in order not to break the unsupported type).

P.S. Syncing EVENT with repetition rule like 'repeat four times every 1 week' syncs well with Caldav_Calendar plugin.

Here is the troublesome EVENT exported from Nextcloud / Calendar webapp:

```
BEGIN:VCALENDAR^M
VERSION:2.0^M
CALSCALE:GREGORIAN^M
PRODID:-//SabreDAV//SabreDAV//EN^M
X-WR-CALNAME:T01^M
X-APPLE-CALENDAR-COLOR:#74e789^M
BEGIN:VTIMEZONE^M
TZID:Europe/Paris^M
X-LIC-LOCATION:Europe/Paris^M
BEGIN:DAYLIGHT^M
TZOFFSETFROM:+0100^M
TZOFFSETTO:+0200^M
TZNAME:CEST^M
DTSTART:19700329T020000^M
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU^M
END:DAYLIGHT^M
BEGIN:STANDARD^M
TZOFFSETFROM:+0200^M
TZOFFSETTO:+0100^M
TZNAME:CET^M
DTSTART:19701025T030000^M
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU^M
END:STANDARD^M
END:VTIMEZONE^M
BEGIN:VEVENT^M
DTSTAMP:20180408T210635Z^M
UID:6be76417-ced2-4400-984c-d156973ae082^M
SUMMARY:Repeat every week until 29-Apr^M
DTSTART;TZID=Europe/Paris:20180401T070000^M
DURATION:PT15M^M
RRULE:FREQ=WEEKLY;UNTIL=20180429T050000Z;BYDAY=SU^M
STATUS:CONFIRMED^M
BEGIN:VALARM^M
TRIGGER:-PT15M^M
ACTION:DISPLAY^M
DESCRIPTION:Repeat every week until 29-Apr^M
END:VALARM^M
END:VEVENT^M
END:VCALENDAR^M
```

**Comment by texxasrulez** [comment]
I cannot recreate the issue
