### ISSUE TITLE
Support for elastic theme on RC 1.4

### ISSUE THREAD

**Issue by gloony** [texxasrulez/Caldav_Calendar#22]
With the RoundCube Beta 1.4 and the theme "elastic", nothing work.
I tried to adaped just the skin to the plugin but it is doesn't enough.

I think it will be a big update but would be awesome too.

**Comment by texxasrulez** [comment]
I plan on working on these but not until the official 1.4 release comes out. I am just making sure all bugs are gone before I start working on this again .... Thanks for your input

**Comment by texxasrulez** [comment]
I am knee deep into this right now. Got a few adjustments to work out. This is a lot of work in itself. May be a bit, but rest assured, it is being worked on ...

**Comment by Sebastiaan76** [comment]
Just wanted to say, I'd love to see this too :). Happy to have a go at helping if you let me know where you are at with it. I'm no PHP guru ( or javascript for that matter ), but keen to learn more. I know Python pretty well, so I'm not totally without ability to learn new things. Is there are WIP somewhere?

**Comment by texxasrulez** [comment]
The current git is my WIP. Most of the aesthetic changes are good to go. My current issue is with dates and times not working properly with RC1.4. 
I have no errors being thrown, so it is a little frustrating to figure this out, but I do not give up easily. Usually just take a step back, think on it a while and then go back to fixing.
Thank you for your interest and offer of help.

**Comment by Sebastiaan76** [comment]
Cool. I only asked as I couldn't see the 'Elastic' skin in your calendar/skins/ directory. Anyway, yes, taking a step back is often useful! :) Great work so far. I'm using it with 'Larry' and it's great!

**Comment by texxasrulez** [comment]
Thanks Sebastiaan76, my linux box took a dump on me and I have been using windows, with that the Github Desktop which said was publishing my changes but was not. The skin should be there now ...

**Comment by texxasrulez** [comment]
> Cool. I only asked as I couldn't see the 'Elastic' skin in your calendar/skins/ directory. Anyway, yes, taking a step back is often useful! :) Great work so far. I'm using it with 'Larry' and it's great!

So you have not tried my Colorful Larry theme here https://github.com/texxasrulez/Roundcube_Skins.

Just hackin' on ya bit in good fun ... Thanks for your support

**Comment by madmath03** [comment]
Hi,

Just wondering, since you tagged this issue for help, what's the current status ? Is there anything special you need help for ?
This plugin looks really good and I would love to see it compatible with Elastic 😉

**Comment by texxasrulez** [comment]
It isn't ready for use and no one is working on it as I am busy with things under the hood. I am not familiar with the elastic theme yet and do not have the time right now. No one has offered any assistance as of yet so fingers crossed someone with the workings of elastic already figured out will offer their time to this project.

**Comment by madmath03** [comment]
I do not guaranty anything, but I will try to take a look at it next week

**Comment by texxasrulez** [comment]
I understand completely. The attempt I have tried so far is not too good either but I appreciate the effort. Many Thanks

**Comment by gloony** [comment]
I make something that work with RoundCube 1.4 and elastic theme : https://github.com/gloony/Caldav_Calendar
I take the last update from libcalendaring / libkolab and calendar from the repo of kolab and start to make your driver work with it.

I don't test with an inferior installation of RoundCube.
I don't test either with another skin than elastic.

But it can give you some idea I guess.

**Comment by fbarel** [comment]
Hello Gloony,
Your solution work fine with RC 1.4.1. Calendar appear well.
But iframe-wrapper ( frame where appear body mail ) still blank even if you select a mail in the list.
Can you check this ?
Best regards

**Comment by gloony** [comment]
> Hello Gloony,
> Your solution work fine with RC 1.4.1. Calendar appear well.
> But iframe-wrapper ( frame where appear body mail ) still blank even if you select a mail in the list.
> Can you check this ?
> Best regards

Have you more information ? I don't have any problem with my mail:
Have you a error on your log or an error on the console.log on your browser ?

**Comment by fbarel** [comment]
I've cleared the cache and every thing is ok. Sorry for that...
Thank's for your work ( you dans Texxasrulez ).
Have a nice day !

**Comment by texxasrulez** [comment]
I have made some progress to this. I will admit it is low on my priority list. Here is a screen shot

![screenshot](https://user-images.githubusercontent.com/10519182/69921863-7c602580-144b-11ea-89d0-d349851c0e83.png)

**Comment by texxasrulez** [comment]
I do believe I have it. I did a lot of changes under the hood and extensive testing is needed. Give me a few days and I will release this new release ... 

![elastic-working](https://user-images.githubusercontent.com/10519182/70175260-3d201780-168b-11ea-98dd-cead8cc0f012.png)

**Comment by texxasrulez** [comment]
Just updated my latest changes. Test it out and let me know. I will close this issue in a few days if no bug reports. Works great for me other than what is in the Readme file in the root of this pluging

**Comment by michieer** [comment]
I get errors about calendar.php and config.inc.php because there are some lines like:
<<<<<<< HEAD
=======
>>>>>>> 921de91e7c5ec3cba0467a7cbe2145c62bfbb6aa

A grep search shows these files:
calendar/calendar.php
calendar/config.inc.php.dist
calendar/drivers/caldav/SQL/mysql.initial.sql
calendar/lib/calendar_ui.php
calendar/localization/de_DE.inc
calendar/localization/en_US.inc

**Comment by michieer** [comment]
Errors when opening site

I get errors about calendar.php and config.inc.php because there are some lines like:
<<<<<<< HEAD

A grep search shows these files:
calendar/calendar.php
calendar/config.inc.php.dist
calendar/drivers/caldav/SQL/mysql.initial.sql
calendar/lib/calendar_ui.php
calendar/localization/de_DE.inc
calendar/localization/en_US.inc

**Comment by texxasrulez** [comment]
This is working so closing ....
