### ISSUE TITLE
"Save as event" broken with RC 1.4

### ISSUE THREAD

**Issue by apircalabu** [texxasrulez/caldav_calendar#23]
- Apache 2.4.43
- PHP 7.4.7 as FPM
- Roundcube 1.4.6
- Nextcloud 18.0.6

Was testing some of the features and when right clicking on an email and choosing "Save as event" I'd get:
PHP Fatal error:  Uncaught Error: Call to undefined method calendar::load_driver() in /usr/share/roundcube/plugins/calendar/calendar.php:3668
After fixing what appeared to be a typo I started seeing another error:
PHP Fatal error:  Uncaught Error: Call to a member function get_message_reference() on null in /usr/share/roundcube/plugins/calendar/calendar.php:3671
Attached a slightly modified version of calendar.php file which appears to work at my end, I'm finally able to save emails as events in the Personal calendar.

[calendar.txt](https://github.com/texxasrulez/caldav_calendar/files/4768800/calendar.txt)

**Comment by texxasrulez** [comment]
I have never even clicked on that. Thanks for finding and reporting it. I have made a fix with commit [c942470](https://github.com/texxasrulez/caldav_calendar/commit/c94247067d14940ac3817e98d632a39e1154739f)

**Comment by apircalabu** [comment]
Thanks for your quick response, appreciated. Your fix does the trick. Cheers :)

**Comment by texxasrulez** [comment]
NP. Thank you and enjoy your weekend.
