### ISSUE TITLE
HTTP error: 404

### ISSUE THREAD

**Issue by Tamsy** [texxasrulez/caldav_calendar#24]
Roundcube v1.4.6
    Nextcloud v18.0.6
    PHP v7.4.7
    MySQL Server v 5.7.30

Testing the latest caldav_calendar (LTS) from git the log throws the following error:

roundcube: <0ef5352c> DAV Error: HTTP error: 404 in /var/www/webmail/plugins/calendar/lib/vendor/sabre/dav/lib/DAV/Client.php on line 231 (GET /?_task=calendar)

What is going wrong here, do I miss some prequisites? Regarding the installation itself I strictly sticked to the instructions.
All tables on mySQL build (including caldav_calendars).

**Comment by texxasrulez** [comment]
A few questions first. 
Is this the first time you have downloaded or are you updating from an older version? A few releases back, I changed the location of sabre so it would be necessary to completely delete the calendar, libcalendaring and libkolab (if present) directories and then upload the latest release.
What driver do you have enabled in the config.inc.php for the calendar? I really have only tested using the 'caldav' option. I have used 'database' as well just to test that and minimal testing at that.
You did good by provided the error from roundcube error log. Is there any showing up in your main system logs? If so, post those as well please.
I have tried to recreate this issue to no avail. 
If you would please indulge me, but can you try doing a "clean" install by deleting all directories of this plugin from your plugins directories and emptying your databases for the caldav_calendar tables. Then download the latest commit from here, not release, but the latest commit that I just uploaded from my system moments ago that works without a hitch for me and upload files back using FTP or your file transfer program of your choice. Using composer to install and update does not work just yet. 
Lets just see if that may fix your issue. I have learned over the years, I am an old man BTW and been an IT Professional for almost 40 years , that sometimes deleting everything and starting from scratch can save many hours of misery. Don't fret about deleting directories and TRUNCATING your database tables for the caldav_calendar as everything will repopulate from NextCloud without losing anything but maybe itip invitations and attachments that you did through RC Interface.
Keep me posted and I will do my best to help figure this out.

**Comment by Tamsy** [comment]
Yup, will do all of that (delete the directories and clean the database tables) and start a fresh install using the latest comit. I will report back to you later today.

And yes, I am using the 'caldav' option and same like you I never use the composer but usually install plugins the old-fashioned way.

Worth to mention that the tables caldav_calendars, calendar_id, caldav_events, event_id and caldav_attachments initially didn't exist and the plugin complained about the missing caldav_calendars-table. Eventually I found them inside ./plugins/calendar/drivers/caldav/SQL and added them to the roundcube database. Maybe this should be added to the install instructions.

**Comment by texxasrulez** [comment]
I appreciate it ... 

There are instructions in the README.md under the "Installation" section saying you must import your SQL schema ...

**Comment by Tamsy** [comment]
Reporting after having installed today's comit:

Exact steps taken:
1. rm -fr ./plugins/calendar, libkolab, libcalendaring.
2. Droped mySQL-tables calendar_oauth_states, calendar_oauth_access_tokens, calendar_oauth_refresh_tokens, caldav_calendars, caldav_events, caldav_attachments.
3. Copied latest calendar, libkolab, libcalendaring to ./plugins
4. Set webserver's  ownership/group to above 3 subdirectories (chown -r ....).
5. Ran on mySQL-database: 
- ./plugins/calendar/SQL/mysql.initial.sql
- ./plugins/calendar/drivers/caldav/SQL/mysql.initial.sql
- ./plugins/calendar/drivers/caldav/SQL/mysql.color.sql
Re-checked, all 6 tables are build correctly.
6. Copied ./plugins/calendar/config.inc.php.dist to ./plugins/calendar/config.inc.php
$config['calendar_driver'] = array("caldav");
$config['calendar_driver_default'] = "caldav";
and
 $config['calendar_preinstalled_calendars'] = array(
    'Nextcloud' => array(
                    'driver'       => 'caldav',
    		    'name'         => '',
                    'caldav_user'  => '%u',
                    'caldav_pass'  => '%p',
                    'caldav_url'   => 'https://cloud.mydomain.com/remote.php/dav/calendars/%u/',
		    'color' 	   =>  '',
                    'showAlarms'   => 1));
7. Activated 'calendar' with List of active plugins (in plugins/ directory) inside ./roundcubedir/config/config.inc.php

After logging in into Roundcube and hitting the Calendar-Button to the left the logfile throws:
- Jul  9 09:44:52 kl roundcube: <55d5a709> DAV Error: HTTP error: 404 in /roundcubedir/plugins/calendar/lib/vendor/sabre/dav/lib/DAV/Client.php on line 231 (GET /?_task=calendar)

Our Nextcloud URL is, different to config.inc.php.dist not at
'caldav_url'   => 'https://www.domain.ltd/nextcloud/remote.php/dav/calendars/%u/',
but at 
'caldav_url'   => 'https:/nextcloud.domain.ltd/remote.php/dav/calendars/%u/',

Maybe the error in the logic lays here?

**Comment by texxasrulez** [comment]
I see your issue. You cannot use subdomains "out of the box" on this plugin. Cross scripting is not allowed, the README.md informs you of this, and thus this is not an issue but a system config issue. There are work arounds but you or your server admin must do some work for it to happen with your apache config.
