### ISSUE TITLE
Uncaught Sabre exception

### ISSUE THREAD

**Issue by Sebastiaan76** [texxasrulez/Caldav_Calendar#27]
Trying to get this to work with a Mailinabox installation. I have a vanilla install of RC 1.4rc1 using mysql Database - all is working ( mail etc. ). Installing this per the instuctions, when I use the calendar button, a blank screen appears. If I 'tail -f' the logs/errors.log I see that I am getting:

```[01-May-2019 17:18:17 Australia/Melbourne] PHP Fatal error:  Uncaught Sabre\HTTP\ClientException: Could not resolve host: www.domain.tld in /usr/local/lib/roundcubemail/plugins/calendar/lib/vendor/sabre/http/lib/Client.php:356```

Any ideas on how/where this might be coming from?

**Comment by Sebastiaan76** [comment]
Never mind - after a bit of 'grep -ri 'www.domain.tld' I soon facepalmed and added the relevant pieces in the config.inc.php file - and, now it works :)

**Comment by texxasrulez** [comment]
I feel ya on that ... I have facepalmed so many times it isn't even funny. Thanks and enjoy!
