### ISSUE TITLE
Changed MySQL initial SQL

### ISSUE THREAD

**Issue by Offerel** [texxasrulez/caldav_calendar#3]
Hi there. I had some errors with "Data too long for column...", thats why i changed calendar/drivers/caldav/SQL/mysql.initial.sql a little bit.

I changed in caldav_calendars column to  ```\`caldav_url` varchar(1000) NOT NULL,``` and in caldav_events:

```
`recurrence` varchar(1000) DEFAULT NULL,
`caldav_url` varchar(1000) NOT NULL,
```
This solved the issue with "Data too long for column...". Maybe 500 chars is enough, but i want to be sure, just in case.

Additionally, i want to try to convert the SQL statement to SQLite also, but in that case some modifications must be done in caldav_driver.php, since SQLite didn't know anything about the NOW() function. We must use datetime('now') there for example and some other modifications.

If i solved the http 401 issue and the looping sync, i can proceed with the migration.

**Comment by texxasrulez** [comment]
I just committed your schema fix to this repo. If solves your 401 and looping issue, let me know and I  can close this issue.  I still haven't been able to reproduce the issue, but with different servers comes different attitudes. Am I right? 
Thanks again for your help ...

**Comment by texxasrulez** [comment]
No news is good news to me. Issue closed
