### ISSUE TITLE
Error in "check calendar" on invitation

### ISSUE THREAD

**Issue by incastrix** [texxasrulez/Caldav_Calendar#3]
when you try to "check calendar" after open invitation mail, roundcube server response 500.

logs/errors
PHP Error: No driver found for calendar "--invitation--itip". (GET /rc/?_task=calendar&view=agendaDay&date=1492682400&itip=INBOX/15%232%3A0&_extwin=1)

BT:
/var/www/html/rc/plugins/calendar/calendar.php.calendar->get_driver_by_cal(): lineno 384	
/var/www/html/rc/plugins/calendar/calendar.php.calendar->_client_event(): lineno 1982	
/var/www/html/rc/plugins/calendar/calendar.php.calendar->itip_events(): lineno 1532	
/var/www/html/rc/plugins/calendar/calendar.php.calendar->calendar_view(): lineno 514	
/var/www/html/rc/program/lib/Roundcube/rcube_plugin_api.php.call_user_func:{/var/www/html/rc/program/lib/Roundcube/rcube_plugin_api.php:491}(): lineno 491	
/var/www/html/rc/program/lib/Roundcube/rcube_plugin_api.php.rcube_plugin_api->exec_action(): lineno 491	
/var/www/html/rc/index.php.{main}(): lineno 283	

I'm going to compare the behaviour of the kolab original plugin.

**Comment by texxasrulez** [comment]
I cannot reproduce the error. Could you give me system details, OS, sql, etc ...

**Comment by texxasrulez** [comment]
Try latest [commit](https://github.com/texxasrulez/Caldav_Calendar/commit/672c6359ebfa8f306ea9aafe5f20bc4a381d49a0) and let me know if this solves your problem. Only the file calendar.php has changed on this.

**Comment by texxasrulez** [comment]
OK, this is strange. It will work sometimes, and sometimes not for me. This one may take a while ...

**Comment by texxasrulez** [comment]
It seems that the insertion of "&itip=INBOX/991%232%3A0" into the URL Is causing the issue. I am getting closer ..

**Comment by texxasrulez** [comment]
Please try [commit](https://github.com/texxasrulez/Caldav_Calendar/commit/833e70832b8b10373fa255600834e7d5bb7d1d10) and let me know if it works. I tested this all morning.

**Comment by texxasrulez** [comment]
I think [commit](https://github.com/texxasrulez/Caldav_Calendar/commit/876315fafe93288d49f84927d998eb06912dcf8f) will fix this issue. Check it out and let us know ... Thanks for the report

**Comment by texxasrulez** [comment]
I do believe I got it this time. I have tested 5 ways to Sunday now and had it accept, decline, maybe, delegate and show calendars. Try latest and let me know if it works for you. Thank you for your report ...

**Comment by incastrix** [comment]
I try latest.
Now "Check Calendar" dialog is showed, but there is no event frame on it.

After accepted an event,  is showed a button to update caledar.
The calendar is just updated when the event is accepted and when press it failed (500).

PHP Error: No driver found for calendar "". (POST /rc-both/?_task=calendar&_action=mailimportitip)

BT:
/var/www/html/rc-both/plugins/calendar/calendar.php.calendar->get_driver_by_cal(): lineno 384	
/var/www/html/rc-both/plugins/calendar/calendar.php.calendar->mail_import_itip(): lineno 3095	
/var/www/html/rc-both/program/lib/Roundcube/rcube_plugin_api.php.call_user_func:{/var/www/html/rc-both/program/lib/Roundcube/rcube_plugin_api.php:491}(): lineno 491	
/var/www/html/rc-both/program/lib/Roundcube/rcube_plugin_api.php.rcube_plugin_api->exec_action(): lineno 491	
/var/www/html/rc-both/index.php.{main}(): lineno 283

**Comment by texxasrulez** [comment]
What is your system details? OS, php version, Roundcube version, etc ..

**Comment by incastrix** [comment]
debian jessie amd64
php 5.6.30-0+deb8u1
rc 1.2.4

**Comment by texxasrulez** [comment]
OK, I cannot recreate. It is working for me. Let me download the whole thing from github and see if I have forgotten to upload some changes I have made in the past.

**Comment by texxasrulez** [comment]
I have dome some modifications when rc 1.2.4 came out and have not updated github as it is still a work in progress. Bear with me ...

**Comment by texxasrulez** [comment]
I have removed the update button as it is redundant. Calendars get updated upon acceptance, maybe or decline ...

**Comment by texxasrulez** [comment]
I have added the update button with some updated code. Let us see if this works as expected.
