### ISSUE TITLE
unable create event , but can edit and delete

### ISSUE THREAD

**Issue by barrettkuo** [texxasrulez/Caldav_Calendar#32]
Hello
I can read, modify and delete the existing calendar events which sync with nextcloud as well.
Just when I create new event on RoundCubeMail GUI, it fails with a message "fails to save changes".

**Comment by texxasrulez** [comment]
What does your logs say?

**Comment by barrettkuo** [comment]
There is no message in log.

**Comment by texxasrulez** [comment]
Have you looked in system logs, not just Roundcube log?

**Comment by marcoprotasi** [comment]
Hello i have same problem, edit and delete ok but dont save new event. 
on roundcube log only errore is:
[19-Jun-2019 19:23:52 Europe/Rome] PHP Fatal error:  Uncaught Sabre\HTTP\ClientHttpException: Internal Server Error in /var/www/rc_webmail.plmdc.net/public_html/plugins/calendar/lib/vendor/sabre/dav/lib/DAV/Client.php:234
Stack trace:
#0 /var/www/rc_webmail.plmdc.net/public_html/plugins/calendar/lib/caldav-client.php(369): Sabre\DAV\Client->propFind('https://sabreda...', Array, 0)
#1 /var/www/rc_webmail.plmdc.net/public_html/plugins/calendar/drivers/caldav/caldav_driver.php(1763): caldav_client->prop_find('https://sabreda...', Array, 0)
#2 /var/www/rc_webmail.plmdc.net/public_html/plugins/calendar/drivers/caldav/caldav_driver.php(153): caldav_driver->_autodiscover_calendars(Array)
#3 /var/www/rc_webmail.plmdc.net/public_html/plugins/calendar/calendar.php(216): caldav_driver->create_calendar(Array)
#4 /var/www/rc_webmail.plmdc.net/public_html/program/lib/Roundcube/rcube_plugin_api.php(440): calendar->startup(Array)
#5 /var/www/rc_webmail.plmdc.net/public_html/index.php(99): rcube_plugin_api->exec_hook('startup', Array)
#6 {main}
  thrown in /var/www/rc_webmail.plmdc.net/public_html/plugins/calendar/lib/vendor/sabre/dav/lib/DAV/Client.php on line 234

The error is create on access to calendar o refresh (f5).
I use Roundcube 1.39 php 7.2 witch SabreDAV, the request to create not send to sabredav server.

Thanks

**Comment by marcoprotasi** [comment]
the function validate($event) on file calendar_driver.php return false, but i  do not understand why.
This a dump for $event array:
Array
(
    [calendar] => 4
    [start] => 2019-06-13T12:00:00
    [end] => 2019-06-13T13:00:00
    [allday] => 1
    [title] => vvvv
    [description] => 
    [location] => 
    [categories] => 
    [free_busy] => busy
    [priority] => 
    [sensitivity] => 
    [status] => 
    [recurrence] => 
    [uid] => E84C04755B21D1D22A5865800E346D87-CF254767FBB8CD9A
    [attachments] => Array
        (
        )

    [attendees] => Array
        (
        )

    [url] => 
)

**Comment by texxasrulez** [comment]
I cannot re-create this issue. I am using in a production setting using RC1.39 and I have a sandbox that I am running on RC1.4 and I am running with no issues or errors in RC log and main system log. 

Can you all give me more information such as is this an all day event, recurring, itip, attachments, etc ... 

Get as detailed as you can and maybe help nail something down.

**Comment by marcoprotasi** [comment]
i change to forck 6ec123321/Caldav_Calendar , i think the problem is in libcalendaring/php 7.2.1

**Comment by henrythemouse** [comment]
My experience with this issue was:

I could edit/delete an event in  a calendar but I couldn't add an event, rc error popup as mentioned above.
I manually removed all caldav_events associated with this calendar from the mysql db
I manually removed this caldav_calendar from mysql db
I reloaded the calendar and was then able to edit/delete/ and create new events.

Only time will tell if this is a permanent fix or if it will reappear at sometime in the future.
I was and am still getting this error in errors.log, although I don't see where functionality is being affected.

`DAV Error: HTTP error: 401 in /var/www/roundcubemail-1.4.rc1/plugins/calendar/lib/vendor/sabre/dav/lib/DAV/Client.php on line 231 (POST /?_task=calendar&_action=refresh)
`

**Comment by MasterMNB** [comment]
I have also the same problem as barrettkuo. 
Roundcube version is 1.39 and Nextcloud version is 16.0.3.
The calendars with existing events from Nextcloud are showing up, i also can edit them.
But if i create an event, i'm only getting a popup with the message "An error has occurred! Error while saving.". No errors in any logs. I tested the removing of the mysql entries and reloading (like mentioned by henrythemouse), but it is still the same problem.

**Comment by MasterMNB** [comment]
```
Array(
[calendar] => 1
[start] => 2019-08-06T12:00:00
[end] => 2019-08-14T13:00:00
[allday] => 1
[title] => NEW-EVENT
[description] => text
[location] => location1
[categories] => Personal
[free_busy] => busy
[priority] =>
[sensitivity] =>
[status] =>
[recurrence] =>
[uid] => 400H04431611D95CF7CA5AF9E58E6CD7-E4D60C90F1C69AAF
[attachments] => Array()
[attendees] => Array()
[url] =>
)
```
without the line: `if (!$this->validate($event)) return false;`

```
PHP Fatal error:  
Uncaught Error: __clone method called on non-object in /var/www/html/plugins/libcalendaring/libvcalendar.php:949\nStack trace:\n#0 /var/www/html/plugins/libcalendaring/libvcalendar.php(900): 
libvcalendar->_to_ical(Array, Object(OldSabre\\VObject\\Component\\VCalendar), false)\n#1 /var/www/html/plugins/calendar/lib/caldav-client.php(291): 
libvcalendar->export(Array)\n#2 /var/www/html/plugins/calendar/drivers/caldav/caldav_sync.php(223): caldav_client->put_event('/remote.php/dav...', Array)\n#3 /var/www/html/plugins/calendar/drivers/caldav/caldav_driver.php(321): 
caldav_sync->create_event(Array)\n#4 /var/www/html/plugins/calendar/calendar.php(1150): caldav_driver->new_event(Array)\n#5 /var/www/html/program/lib/Roundcube/rcube_plugin_api.php(493): 
calendar->event_action()\n#6 /var/www/html/index.php(295): rcube_plugin_api->exec_action('calendar.event')\n#7 {main}\n  thrown in /var/www/html/plugins/libcalendaring/libvcalendar.php on line 949, referer: https://x/email/?_task=calendar
```

**Comment by MasterMNB** [comment]
I tested also the database driver and had similar results (except that an edit results in an error).
```
PHP Fatal error:  Uncaught Error: __clone method called on non-object in /var/www/html/plugins/roundcube-plugins/calendar/drivers/database/database_driver.php:615
Stack trace: /var/www/html/plugins/roundcube-plugins/calendar/drivers/database/database_driver.php(674): database_driver->_save_preprocess(Array)
#1 /var/www/html/plugins/roundcube-plugins/calendar/drivers/database/database_driver.php(482): database_driver->_update_event(Array, true)
#2 /var/www/html/plugins/roundcube-plugins/calendar/calendar.php(1161): database_driver->edit_event(Array)
#3 /var/www/html/program/lib/Roundcube/rcube_plugin_api.php(493): calendar->event_action()
#4 /var/www/html/index.php(295): rcube_plugin_api->exec_action('calendar.event')
#5 {main}\n  thrown in /var/www/html/plugins/roundcube-plugins/calendar/drivers/database/database_driver.php on line 615, referer: https://x/?_task=calendar
```
That means the event data must be wrong. 
But i don't see the Problem why.

**Comment by MasterMNB** [comment]
in $event the elements "start" and "end" should be more like this:
```
[start] => DateTime Object([_dateonly] => 1 [date] => 2019-08-06 00:00:00.000000 [timezone_type] => 3 [timezone] => UTC)
[end] => DateTime Object([_dateonly] => 1 [date] => 2019-08-08 01:00:00.000000 [timezone_type] => 3 [timezone] => UTC)
```
and not (what i get):
```
[start] => 2019-08-06T12:00:00
[end] => 2019-08-14T13:00:00
```
