### ISSUE TITLE
creating/editing calendars

### ISSUE THREAD

**Issue by henrythemouse** [texxasrulez/Caldav_Calendar#33]
I'm using this plugin without nextcloud, just roundcubemail and a davical server and it's working perfectly with the Larry skin. It retrieved and displayed my calendars on first load. Thank you for making this happen, it is very useful. I too am looking forward to being able to use the new Elastic skin.

I see three issues with the ui, the 'create', 'edit' and 'delete' functions don't work. The 'create' and 'edit' functions generate a popup dialog with this error: 'Server Error! (Internal Server Error)'.  I'm thinking that these errors are likely permission errors on the part of the server and not a problem with your calendar plugin. Is it even practical to do these sort of operations from within roundcubemail? 

Thanks again

**Comment by texxasrulez** [comment]
I only support Nextcloud integration. I am sorry but do not have the time to make this work for all. That is the reason I started this to begin with as I couldn't find anything that worked good with Nextcloud. I am closing this issue and thank you for your interest.

**Comment by henrythemouse** [comment]
I understand, these things take a lot of personal time.
However, whatever you do with this project will apply generally to most 
caldav servers. For that effort, I thank you.
Roundcubemail has needed a caldav calendar for a very long time and 
combining your efforts with the Elastic theme will put Roundcubemail 
back in my browser.

**Comment by texxasrulez** [comment]
I agree it should be easy to make one that will work with all, but I really don't have the level of skills to make work. I know just enough to be dangerous :-) .
I would give my time to one for all if a few people were willing to work on it as well. That would be a great plugin. I should fork this for support with all caldav servers for that reason and post for help and see what happens.
Thanks again for your input ...
