### ISSUE TITLE
if signing with email under NC, unable to open calendar (NC use uid too)

### ISSUE THREAD

**Issue by ledufakademy** [texxasrulez/Caldav_Calendar#34]
NC waiting for
https://nuage.domain.com/remote.php/dav/calendars/myUser.domain/personal/

Your plugin send :
Resource "https://nuage.domain.com/remote.php/dav/calendars/myUser@domain.com/%n/" has no collections

Could you help me to add a field (for end user) in setup in order to let  end user fill the cal Dav URL ?

**Comment by MasterMNB** [comment]
You try this in roundcubeinstall/plugins/calendar/config.inc.php:
```
$config['calendar_preinstalled_calendars'] = array(
    'Nextcloud' => array(
        'driver'      => 'caldav',
        'caldav_user' => '%l.domain',
        'caldav_pass' => '%p',
        'caldav_url' =>'https://nuage.domain.com/remote.php/dav/calendars/%l.domain/',
        'color'       => '#0000FF',
        'showAlarms'  => 1),
);
```
If you not define "calendar_preinstalled_calendars" or "calendar_caldav_url" you can add it manually in the user interface:
![image](https://user-images.githubusercontent.com/3178390/62777616-51258500-baae-11e9-87d1-fdc2091d5ecc.png)

**Comment by texxasrulez** [comment]
Many thanks to MasterMNB for your help.
