### ISSUE TITLE
display issue for longer events [UI]

### ISSUE THREAD

**Issue by MasterMNB** [texxasrulez/Caldav_Calendar#36]
If i insert a longer event it looks like this:
![image](https://user-images.githubusercontent.com/3178390/64689217-328c2280-d48e-11e9-9ee3-fa3d3365e902.png)

**Comment by texxasrulez** [comment]
I cannot recreate. Please give as detailed description as you can. Server, database, log entries,  etc ...

Sure helps out the debugging process when you can give exact details no matter how minuscule.

**Comment by MasterMNB** [comment]
**Versions:**
Roundcube version is 1.4-rc1 (with the design "Larry" active)
Nextcloud version is 16.0.4.1  
PHP version is 7.2.21  
Mariadb version 10.4.7  

**There are no error messages or log entries.**

**Additional Roundcube plugins:**
- contextmenu_folder
- infinitescroll
- carddav
- advanced-search
- thunderbird_labels

**This is the HMTL code of the event:**
```
<div class="fc-event-container" style="position:absolute;z-index:8;top:0;left:0">
  <div class="fc-event fc-event-skin fc-event-hori fc-event-draggable fc-event-start fc-event-cat-personal fc-event-cal-13 cal-event-status-confirmed" style="position: absolute; left: 99px; background-color: rgb(122, 67, 67); border-color: rgb(122, 67, 67); width: 0px; top: 205px;" tabindex="0" title="test" aria-label="test, September 3 2019 until September 19 2019">
    <div class="fc-event-inner"><span class="fc-event-title">test</span></div>
  </div>
  <div class="fc-event fc-event-skin fc-event-hori fc-event-draggable fc-event-cat-personal fc-event-cal-13 cal-event-status-confirmed" style="position: absolute; left: 0px; background-color: rgb(122, 67, 67); border-color: rgb(122, 67, 67); width: 99px; top: 363px;" tabindex="0" title="test" aria-label="test, September 3 2019 until September 19 2019">
    <div class="fc-event-inner"><span class="fc-event-title">test</span></div>
  </div>
  <div class="fc-event fc-event-skin fc-event-hori fc-event-draggable fc-event-end fc-event-cat-personal fc-event-cal-13 cal-event-status-confirmed" style="position: absolute; left: 0px; background-color: rgb(122, 67, 67); border-color: rgb(122, 67, 67); width: 381px; top: 521px;" tabindex="0" title="test" aria-label="test, September 3 2019 until September 19 2019">
    <div class="fc-event-inner"><span class="fc-event-title">test</span></div><div class="ui-resizable-handle ui-resizable-e">&nbsp;&nbsp;&nbsp;</div>
  </div>
</div>
```

**Comment by texxasrulez** [comment]
Download latest update. Will close issue in a few days if no report

**Comment by texxasrulez** [comment]
I just setup a three week long event and posting my screenshot .. 

![long-event](https://user-images.githubusercontent.com/10519182/70399561-f5c2bf80-19d9-11ea-801e-72d9d10658eb.png)

How about your end?

**Comment by MasterMNB** [comment]
At the moment i can not test this version, because the manual creation of calendars are not working (driver selection is not coming up for that). And the only way i get a username and password is over the app password function in Nextcloud or over OpenId connect.

But maybe this helps to test this, 
in the config i changed the first day of the week(forgot to mention this :sweat_smile: ):
$config['calendar_first_day'] = 1;

**Comment by texxasrulez** [comment]
I changed to Monday first day of week and didn't have any display issues.
I am sorry to hear about your database issue. 

I can get database to work by itself. I know in the past you could have multiple drivers enabled. I will investigate. It will be a little difficult as I am not getting any errors at the moment.

Do you have any errors that could help out? We will figure this out

**Comment by texxasrulez** [comment]
Download latest commit and will fix this issue
