### ISSUE TITLE
Invitation timezone problem

### ISSUE THREAD

**Issue by skug67** [texxasrulez/Caldav_Calendar#4]
When I create an appointment in the caldav calendar it shows up on Nextcloud with the correct timezone, but the emailed invitation is incorrect -- my local timezone is America/New_York and it always shows up with a time 4 hours too early; which suggests that it's adjusting from GMT twice.  Any thoughts on how to fix this?

**Comment by skug67** [comment]
Correction -- the problem only manifests when sending to Microsoft Outlook 2013.  Not quite sure what to make of it....

**Comment by texxasrulez** [comment]
I am unable to recreate. I do not have MS Outlook to test.
