### ISSUE TITLE
Using app password with Nextcloud

### ISSUE THREAD

**Issue by RabbitDuck** [texxasrulez/Caldav_Calendar#43]
Hi,

Nextcloud recommends using app password for better security.
Is it possible to save the app password in the calendar plugin's database, and use it to connect to nextcloud?

We use email address as the login name of nextcloud and create app password for Caldav/Carddav clients.

Thanks!

**Comment by texxasrulez** [comment]
I can look into it, but I am not a programmer per se. I am just an old man who knows a little bit. 

I would love to start, or at least join in, a group to make the best caldav calendar plugin available for Roundcube.
 
Who is with me?

**Comment by MasterMNB** [comment]
Hi,
at the moment you could add every single calendar manually in the user UI, it's not perfect but it works (also with the app password). But you should not edit this calendar(still not stable). If you need to edit it, remove and recreate it.
![image](https://user-images.githubusercontent.com/3178390/68990666-12922a00-0856-11ea-85c0-5343ffb7a536.png)

**Comment by texxasrulez** [comment]
Download latest update. Will close issue in a few days if no report
