### ISSUE TITLE
Last update introduced a few syntax errors

### ISSUE THREAD

**Issue by MasterMNB** [texxasrulez/Caldav_Calendar#44]
Error message:
`PHP Parse error:  syntax error, unexpected '<<' (T_SL) in /var/www/html/plugins/roundcube-plugins/calendar/calendar.php on line 520`

This Lines are the cause of it (in a few files):
```
<<<<<<< HEAD
======
>>>>>>> 921
```
I think they sneaked into the code on an offline merge. :wink: 

As @michieer listed in #22 
The problem is in this files:
calendar/calendar.php
calendar/config.inc.php.dist
calendar/drivers/caldav/SQL/mysql.initial.sql
calendar/lib/calendar_ui.php
calendar/localization/de_DE.inc
calendar/localization/en_US.inc

**Comment by texxasrulez** [comment]
Strange ... Fixed what was listed ... Will check for more when I get home from work

**Comment by texxasrulez** [comment]
Should be fixed. Using Desktop Github on Windows and just don't like it. I miss my linux box
