### ISSUE TITLE
Caldav search

### ISSUE THREAD

**Issue by vogll** [texxasrulez/Caldav_Calendar#46]
Hi,
I have nextclou 17.0.2 and Caldav_calendar from git installed.
Only default preinstalled calendar show for me. When I try to browse user calendars this error apear :

PHP Fatal error:  Uncaught Error: Call to a member function search_calendars() on null in /var/www/html/roundcube/plugins/calendar/calendar.php:1096

can you help me ?

**Comment by texxasrulez** [comment]
I cannot recreate this error

Have you logged into you nextcloud account and let it build your calendar first? From the sounds of the error, it is looking at an empty calendar ...

**Comment by trogper** [comment]
@vogll try replacing `$driver` with `$this->driver` on line 1096. I'm having similar issues (member function on null) on many different lines, this has fixed the issue every time

**Comment by texxasrulez** [comment]
I have provided an update on missed $driver to $this->driver ... Latest commit will fix this ...
