### ISSUE TITLE
When Database prefix is used, sql script has be be manually edited

### ISSUE THREAD

**Issue by StefCGN** [texxasrulez/Caldav_Calendar#47]
Hi,
thanks for the calendar, i am just installing it.
It has an error in the MySQL script, which references to:
`REFERENCES `users`(`user_id`) ON DELETE CASCADE ON UPDATE CASCADE`

This line has to be edited, when using roundcube prefixes.

**Comment by texxasrulez** [comment]
Can you be more specific and provide log info, screen captures, whatever you can to help? I have this installed on several sql servers with prefixes and never had an issue

**Comment by texxasrulez** [comment]
Since no reply or more info, I am closing this issue
