### ISSUE TITLE
The support for elastic skin is very well done

### ISSUE THREAD

**Issue by henrythemouse** [texxasrulez/Caldav_Calendar#49]
As I'm sure many other user have been awaiting the support for elastic, I too have been checking back now and then to see if was ready. I just checked today and found that you had finished it. The installation was simple as usual and worked without a hitch. I just wanted to let you know that I really appreciate the work you've done. The result looks fantastic.

Thanks

**Comment by texxasrulez** [comment]
Well thank you very much henrythemouse. You are the VERY FIRST PERSON to thank me for my work on this fork. 
I not only made this compatible with the Elastic theme, but I did a major overhaul under the hood on this and caught up with the official Kolab version. One bad thing on that is I kinda reintroduced the All Day recurring annual day before event bug again, but outside of that, I am still happy with the results myself. It does make me feel even better that I got me a Bravo Zulu (Military speak for Good Job, Yes I am a Veteran) from a satisfied user. Thank you for that. Just let me fix the All Day thing again and I will be super happy. 
I do thank you very much and hope nothing but the best for you henrythemouse
