### ISSUE TITLE
"caldav_calendar" vs "caldav_calendar_te"

### ISSUE THREAD

**Issue by uli-heller** [texxasrulez/caldav_calendar#5]
Hey Glen,

is it an issue referencing "caldav_calendar_te" from within "caldav_calendar"?
The last two commits to contain such references, see a0638e64c7a8f3cb14231 file composer.json
for example.

Best regards, Uli

**Comment by texxasrulez** [comment]
Not really. Only if you install using composer, but I specify in readme not to update that way. It is a work in progress and will get fixed here and there when I can find the time

**Comment by texxasrulez** [comment]
Fixed Repo name in commit (ca75da0) and will close this issue ... Thanks for double checking me @uli-heller
