### ISSUE TITLE
No driver name found in GPC

### ISSUE THREAD

**Issue by inpos** [texxasrulez/Caldav_Calendar#5]
When try to print any calendar view there is no events in the print-preview.
And the following error in log:
`May 17 19:01:02 mail roundcube: <h2u9hgjk> PHP Error: No driver name found in GPC. (GET /?_task=calendar&_action=load_events&source=1&start=1493586000&end=1497214800&_=1495036861226)`

**Comment by texxasrulez** [comment]
Issue Confirmed. Give me a little time to find the culprit ... Thanks again for your contribution ...

**Comment by texxasrulez** [comment]
Should be fixed now. Check out [https://github.com/texxasrulez/Caldav_Calendar/commit/79eb611bec99f26230c6be86b275b4b40124e53f](latest commit)

**Comment by inpos** [comment]
Yeah, everything works fine. Thanks!
