### ISSUE TITLE
attachments

### ISSUE THREAD

**Issue by inpos** [texxasrulez/Caldav_Calendar#6]
- Open attachment tab
- Choose file
- Press Upload
Nothing happens

When Drag'n'Drop file to attachment tab it's trying to upload and crash to error:
`May 17 19:28:17 mail roundcube: PHP Fatal error:  Call to undefined function Q() in /var/www/roundcubemail/plugins/libcalendaring/libcalendaring.php on line 1084`

**Comment by inpos** [comment]
After replace all `Q(` by `$this->rc->Q(` Drag'n'Drop started working.

**Comment by texxasrulez** [comment]
Nice catch. Replace `rcube::Q` with  `rcube_utils::rep_specialchars_output` on line 1084. This is the fix I am placing in branch. 
I haven't used the attachment feature, so I never caught that, great job .. Thanks for your contribution.

**Comment by inpos** [comment]
When Drag'n'Drop there is error:
`May 19 11:11:25 mail roundcube: PHP Fatal error:  Call to undefined function Q() in /var/www/roundcubemail/plugins/libcalendaring/libcalendaring.php on line 1095`
I think libcalendaring.php contains multiple calls of Q()

**Comment by inpos** [comment]
When try to choose file and click upload nothing happens.
I mean when click to "upload" nothing happens.
Firefox debugger show this error:
`ReferenceError: JS_OBJECT_NAME is not defined
	

<!DOCTYPE html>

	`

**Comment by texxasrulez** [comment]
I cannot recreate issue. Using the fix you provided above gave several other error messages is why I went the route I went ... What browser are you using?

**Comment by texxasrulez** [comment]
OK, upon investigating further, I made a boneheaded mistake on code yesterday. I had fixed the Q deprecated and evidently didn't upload to github and saw that I already changed to rcube::Q so thus the weird specialchars option. It should be $content .= rcube::Q($attachment['name']); @ line 1095.
 I went ahead and copied and pasted my libcalendaring.php up to github, ... This should fix your issue. 

Sorry about that. My Father has been pretty sick the last few days and I guess I was more distracted than I thought.

**Comment by inpos** [comment]
I use Firefox 45.9.0 on Debian Stretch

**Comment by inpos** [comment]
Here is my patch
https://pastebin.com/ENQTj6cv

**Comment by inpos** [comment]
Now upload and drag'n'Drop works fine.
But preview of attached images don't work.
When click on image blank preview window appear and error in access log:
`"GET /?_task=calendar&_id=9&_event=1619&_cal=1&_action=get-attachment&_extwin=1 HTTP/1.1" 404`

**Comment by inpos** [comment]
after refresh page attachment disappear

**Comment by texxasrulez** [comment]
Unable to recreate.

**Comment by texxasrulez** [comment]
I noticed an error during this issue here and found deprecated show_bytes. I just committed it .. Maybe this can solve your issue. Also, since I cannot reproduce the preview error you are experiencing, tell me what other plugins you use and see if that may be something ...
