### ISSUE TITLE
Skip already existent calendars - but per user

### ISSUE THREAD

**Issue by pitsail** [texxasrulez/caldav_calendar#8]
I think that there should be one more condition in where clause in calendar/drivers/caldav/caldav_driver.php, line 163.
(in other drivers too)

So far there is only calendar url permitted across all users. In my cause it means I cannot add shared calendars that are already in use by their owners.
I suggest to change the query to:

$result = $this->rc->db->query("SELECT * FROM ".$this->db_calendars." WHERE **user_id=”. $this->rc->user->ID.” AND** caldav_url LIKE ?", str_replace('@', '%40', $calendar['href']));
Now we avoiding duplicates only within users’ scope.

Now we avoiding duplicates only within users’ scope.

BTW/OT (or else) shouldn’t shared calendars be imported automatically or I messed up something?

**Comment by texxasrulez** [comment]
I have shared calendars with co-workers and I have no issues that I am aware of.

The URL breakdown for shared calendar is as follows:
https://www.domain.ltd/cloud/remote.php/dav/calendars/test@domain.ltd/work_shared_by_gene@domain.ltd/

What are you trying to accomplish? User A needs User B blah blah ..

**Comment by pitsail** [comment]
I was just unable to add second calendar with same source url.
So i dig the code and found that sql check in caldav_driver.php (line 163) is performed before adding any new calendar and therefore prevents duplicate source url's in db table.
I made that change and now i can use same source url calendar among different users.

I'm using SOGo DAV and did not find (look for) any other URL than that provided by SOGo GUI...
The SQL query is OK when using URL schema you mentioned but in my case it fails.

Thats all.

**Comment by pitsail** [comment]
Apologies

The problem was on my site.

In config.inc.php i set
'caldav_url'   => 'https://DOMAIN/SOGo/dav/%u/Calendar/personal/'

after i've changed it to
'caldav_url'   => 'https://DOMAIN/SOGo/dav/'

it started working as expected.
So my fault.

I still cannot see any sharing options when I open 'Edit/share calendar' but I guess I can be missing something again.
Am I?

**Comment by texxasrulez** [comment]
It is all good .. ;-) I am glad it is working as expected. Have a great day
